# Generated by Django 4.0.6 on 2022-08-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='PerformanceNote',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
