# Generated by Django 4.0.6 on 2022-08-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_performance_cy'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='MeasurementSystem',
            field=models.CharField(default='inches', max_length=20),
            preserve_default=False,
        ),
    ]
