# Generated by Django 4.0.6 on 2022-08-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_event_measurementsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='Archive',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
