# Generated by Django 4.0.6 on 2022-08-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_performance_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='MarkRawLarge',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='MarkRawSmall',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
