# Generated by Django 4.0.6 on 2022-08-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_performance_markrawlarge_performance_markrawsmall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='MarkRaw',
        ),
    ]
