# Generated by Django 4.0.6 on 2022-09-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_performance_confirmed_user_maintainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='Locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='performance',
            name='PerformanceNote',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
